---
# file: roles/fileserver/tasks/config_network.yml

#============================================================================ 
# network interfaces configuration
#============================================================================
- hosts: headnode
  vars_files:
    - [ "{{ansible_env.PWD}}/group_vars/all_local", "{{ansible_env.PWD}}/group_vars/all" ]
  tasks:
    - name:
      include: '../../../globals.yml'   # Defines default_interface variable
    - debug: var=default_interface

    - name: Stop default network interface device
      shell: bash -lc "ifdown {{default_interface}}"
      register: output
    - debug: var=output
      
    - name: Edit /etc/network/interfaces
      template: src=../templates/interfaces.j2 dest=/etc/network/interfaces mode=0644 backup=yes
    
    - name: Restart default network interface device
      shell: bash -lc "ifup {{default_interface}}"
      register: output
    - debug: var=output