---
# file: docker.yml
# The ordering of these operations matters
- include: common.yml               # Common settings
- include: db.yml                   # Postgresql server
- include: webserver.yml            # Apache2 server
- include: gridengine_master.yml    # Gridengine master host
- include: gridengine_clients.yml   # Gridengine exec host
- include: iontorrent_master.yml    # Headnode
