---
# file: globals.yml
#Define the S5_virtual_guest variable
- name: 
  stat: path=/etc/init.d/mountExternal
  register: p

- name: set_fact S5_virtual_guest
  set_fact:
    S5_virtual_guest: "{{p.stat.exists|bool}}"
  
- debug: var={{S5_virtual_guest}}

# Load the platform-specific variables, if the file exists
- name: 
  stat: path='group_vars/{{ansible_product_name}}'
  register: p
- include_vars: 'group_vars/{{ansible_product_name}}'
  when: p.stat.exists
# ...or if its an S5, load the S5 variables
- include_vars: 'group_vars/S5'
  when: S5_virtual_guest

# Define the default_interface
# By design, it is first slot on the PCI network card for T7500 or first on-board NIC for all others
# Either em1, eth0
- name: define the interface string for T7500
  set_fact: default_interface=eth0
  when: ansible_product_name == "Precision WorkStation T7500"
- name: define the interface string for non-T7500
  set_fact: default_interface=em1
  when: ansible_product_name != "Precision WorkStation T7500"
- name: set the default_interface
  set_fact: default_interface={{ansible_default_ipv4.interface|default(default_interface)}}
- debug: var=default_interface

- debug: var=default_interface
