---
# file: gridengine_master.yml
- hosts: gridengine_master
  roles:
    - gridengine_master
  tags:
    - gridengine
  tasks:
    - include: roles/iontorrent_master/handlers/main.yml  # restart ion daemons
