---
# file: nfs_client.yml
- hosts: headnode:computes
  roles:
    - nfs_client
  tags:
    - nfs_client
  vars_files:
    - [ "group_vars/all_local", "group_vars/all" ]
  vars:
    - startline: "#start TSconfig added mountpoints"
    - endline: "#end TSconfig added mountpoints"
