---
# file: roles/igv/tasks/main.yml

- name:
  include: '../../../globals.yml'
#-----------------------------------------------------------------------------
# Install system packages for igv
#-----------------------------------------------------------------------------
- name: Install tomcat server
  apt: name={{ item }} state=present force=yes
  with_items:
    - tomcat7
    - tomcat7-admin
  
#-----------------------------------------------------------------------------
# Install Ion Torrent Packages for igv
#-----------------------------------------------------------------------------
- name: Install packages for igv node
  apt: name={{ item }} state=present force=yes
  with_items:
    - ion-jk
    - ion-igv
