---
# file: roles/nfs_client/tasks/main.yml
#-----------------------------------------------------------------------------
# Mount NAS resources
# Except, if a node is exporting, then it should not mount its own resource
#-----------------------------------------------------------------------------
- name: DEBUG
  debug: msg="No NFS mounts to be configured"
  with_items: nas_mounts
  when: nas_mounts|default(None) == None
- name: DEBUG
  debug: msg=""
  with_items: nas_mounts
  when: nas_mounts|default(None) != None
  
- name: Create external storage mountpoints
  shell: bash -lc 'if [ ! -d {{ item.mountpoint }} ]; then mkdir -p {{ item.mountpoint }}; chmod 0777 {{ item.mountpoint }}; fi'
  with_items: nas_mounts
  when: nas_mounts|default(None) != None and item.name != ansible_hostname
  
- name: Create fstab entry
  lineinfile: dest=/etc/fstab
                state=present
                regexp='{{item.name}}:{{item.directory}}.*'
                line='{{item.name}}:{{item.directory}} {{item.mountpoint}} nfs defaults 0 0'
  with_items: nas_mounts
  when: nas_mounts|default(None) != None and item.name != ansible_hostname

- name: Execute mount command
  shell: bash -lc 'if ! mount|grep "{{ item.name }}:{{ item.directory }}"; then mount {{ item.mountpoint }}; fi'
  with_items: nas_mounts
  when: nas_mounts|default(None) != None and item.name != ansible_hostname
  

#-----------------------------------------------------------------------------
# Remove what we have done - for development only
#-----------------------------------------------------------------------------
#- name: Unmount mountpoints
#  when: (nas_mounts is defined)
#  shell: bash -lc 'umount {{item.mountpoint}}'
#  with_items:
#    - "{{nas_mounts}}"
#  ignore_errors: yes
#  tags: delete
#    
#- name: Delete mountpoints
#  when: (nas_mounts is defined)
#  file: dest={{item.mountpoint}}
#          state=absent
#          recurse=no
#  with_items:
#    - "{{nas_mounts}}"
#  tags: delete
#          
#- name: Remove fstab entry
#  when: (nas_mounts is defined)
#  lineinfile: dest=/etc/fstab
#                state=absent
#                regexp='{{item.name}}:{{item.directory}}.*'
#  with_items:
#    - "{{nas_mounts}}"
#  tags: delete
